# Generated by Django 3.0.3 on 2020-02-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_patient',
        ),
    ]
